### ISSUE TITLE
Add examples folder with some basics use case

### ISSUE THREAD

**Issue by eddieraa** [eddieraa/registry#2]

**Comment by gedw99** [comment]
Yes please :) 

@eddieraa really cool project. Will def want to contribute

**Comment by gedw99** [comment]
Actually the samples are ok now.

just a few side cases would be nice

**Comment by eddieraa** [comment]
Yes, I do that as soon as possible. 
And yes Nats is very good product

I you want to contribute, you're welcome

**Comment by gedw99** [comment]
Yep will be contributing . It’s very nice system
